name = input("What is our name:")
hobby = input("What is your hobby?")
fav_number = int(input("What's your favorite number?"))
fav_color = input("What's your favorite color?")
fav_food = input("What's your favorite food?")
fav_place = input("What's your favorite place?")
fav_thing = input(";What's your favorite thing?")
fav_move = input ("What's your favorite move?")
fav_game = input("What's your favorite game?")
print(name)
print(hobby)
print(fav_number)
print(fav_color)
print(fav_food)
print(fav_place)
print(fav_thing)
print(fav_move)
print(fav_game)
print(thend)
